# Generated by Django 6.0.3 on 2026-03-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('platform', models.CharField(choices=[('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('blinkit', 'Blinkit'), ('zepto', 'Zepto')], max_length=20)),
                ('upi_id', models.CharField(max_length=100)),
                ('avg_weekly_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
